### ISSUE TITLE
"undefined method `succ' for nil:NilClass"

### ISSUE THREAD

**Issue by jchannon** [jondot/version_bumper#4] opened 2013-06-26 14:07 UTC
In version.rb I think you need to do this on line 25:

`version = @v[part] = @v[part].to_i.succ`

**Comment by jondot** [comment] 2013-06-26 14:16
Hi there,
`#succ` was used because it should do "the right thing", with numbers - it will take a next number and with letters it should take the next letter, example:  

```
"21".succ
=> "22"
"a".succ
=> "b"
```

I think the `nil` error might be because `@v[part]` itself doesn't exist in your case.

**Comment by jchannon** [comment] 2013-06-26 14:20
I was calling it like so:

def env_buildversion
  bumper_version.to_s
end

task :currentversion do
   bumper_version.bump_build
   bumper_version.write('VERSION')
   puts env_buildversion
end

**Comment by jondot** [comment] 2013-06-26 14:22
OK, and how does a sample of your version look like?

**Comment by jchannon** [comment] 2013-06-26 14:27
I've uninstalled and reinstalled the gem and my sample code above works
fine now.

Odd!

Thanks

**Comment by jondot** [comment] 2013-06-26 14:31
Happy it works :)
Feel free to close this issue once you feel comfortable that the issue is resolved :+1:

**Comment by jchannon** [comment] 2013-06-26 14:44
Thanks for the help!

**Comment by jchannon** [comment] 2013-06-27 12:46
I've just installed to a prod server and get the same error:(

**Comment by jondot** [comment] 2013-06-27 12:49
That's strange. From what you're said before, if you'll install again, it will be resolved?
Sounds like a network cache / CDN problem? are you under any kind of corporate / internal caching proxy?

How about doing a `gem list -d version_bumper` and taking note of what exactly is installed right now, and then do the same thing you did to resolve earlier, and run `gem list -d version_bumper` again to see what's changed.

**Comment by jchannon** [comment] 2013-06-27 12:49
All fixed, permissions and wrong version format! Thanks

**Comment by jondot** [comment] 2013-06-27 12:51
OK so if it's a permission problem that relates to your server's setup. When are you getting that? can you paste a terminal output?

**Closed as completed** 2013-06-27 12:51 UTC

**Comment by jchannon** [comment] 2013-06-27 13:18
Are you about for a chat on Jabbr.net?

**Comment by jondot** [comment] 2013-06-27 13:22
not familiar with it, feel free to email me at dotan@paracode.com

**Comment by jchannon** [comment] 2013-06-27 13:23
its a oss chat room. I'm running rake via Team City and its complaining that it cant find VERSION. I'm guessing this is a relative path issue
